name: 线阵相机管理服务打包发布

on:
  push:
    tags:
      - jade_tools-v*

jobs:
  packing:
    name: 线阵相机管理服务打包发布
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ] #, "macos-latest", "windows-latest"
    steps:
      - name: 下载代码
        uses: actions/checkout@v3
        with:
          repository: jadehh/jade_tools
          ref: ds_manage_service
          path: code
          token: ${{ secrets.GH_PAT }}

      - name: 获取版本号
        id: get_version
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "version=${tag/jade_tools-v/}" >> $GITHUB_OUTPUT
          echo "tag_name=${tag}" >> $GITHUB_OUTPUT

      - name: 编译打包
        uses: addnab/docker-run-action@v3
        with:
          image: jadehh/jade-tools:1.0.3-opencv-4.3.0-cuda-10.0-cudnn7-devel-ubuntu18.04
          options: -v ${{ github.workspace }}/code:/code
          run: |
            cd code && mkdir -p build && cd build
            cmake .. -D CMAKE_INSTALL_PREFIX="/code/Output" \
                     -D SQLITE3_DIR="/usr/include" \
                     -D OPENSSL_DIR="/usr/include" \
                     -D BREAKPAD_DIR="/usr/local/breakpad" \
                     -D SPDLOG_DIR="/usr/include" \
                     -D OPENCV_DIR="/usr/local/opencv"            
            make -j$(nproc) && make install
            cd /code && tar -czvf jade_tools-${{ steps.get_version.outputs.version }}-x64-linux.tar.gz Output/
            md5sum jade_tools-${{ steps.get_version.outputs.version }}-x64-linux.tar.gz > jade_tools-${{ steps.get_version.outputs.version }}-x64-linux.tar.gz.md5

      - name: 生成更新日志
        run: |
          cd code
          cmake -P .cmake/extractChangelog.cmake
          echo "## 下载信息" >> RELEASE_NOTES.md
          echo "| 文件名 | MD5校验值 | 下载链接 |" >> RELEASE_NOTES.md
          echo "|--------|----------|----------|" >> RELEASE_NOTES.md
          file="jade_tools-${{ steps.get_version.outputs.version }}-x64-linux.tar.gz"
          md5=$(cat "${file}.md5" | awk '{print $1}')
          download_url="https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.tag_name }}/$file"
          echo "| $file | \`$md5\` | [下载]($download_url) |" >> RELEASE_NOTES.md

      - name: 发布版本
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          name: "线阵相机管理服务 ${{ steps.get_version.outputs.version }}"
          body_path: "code/RELEASE_NOTES.md"
          files: |
            code/jade_tools-${{ steps.get_version.outputs.version }}-x64-linux.tar.gz
            code/jade_tools-${{ steps.get_version.outputs.version }}-x64-linux.tar.gz.md5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}