set(OPENSSL_DIR "" CACHE PATH "location of libraries")
if (NOT DEFINED OPENSSL_DIR OR OPENSSL_DIR STREQUAL "")
    message("-- Find OPENSSL_DIR failed,Please set OPENSSL_DIR with -D OPENSSL_DIR=/usr/local/OPENSSL")
    option(BUILD_OPENSSL_ON "Build OPENSSL" OFF)
else ()
    message("-- Find OPENSSL_DIR success:${OPENSSL_DIR}")
    if (WIN32)
        set(OPENSSL_LIBS libssl libcrypto)
    else ()
        set(OPENSSL_LIBS ssl crypto)
    endif ()
    option(BUILD_OPENSSL_ON "Build OPENSSL" ON)
    set(OPENSSL_INCLUDE_DIR "${OPENSSL_DIR}/include")
    set(OPENSSL_LIB_DIR "${OPENSSL_DIR}/${TARGET_ARCHITECTURE}/lib/")
    include_directories(${OPENSSL_INCLUDE_DIR})
    link_directories(${OPENSSL_LIB_DIR})
endif ()
