set(SQLITE3_DIR "" CACHE PATH "location of libraries")
if (NOT DEFINED SQLITE3_DIR OR SQLITE3_DIR STREQUAL "")
    message("-- Find SQLITE3_DIR failed,Please set SQLITE3_DIR with -D SQLITE3_DIR=/usr/local/SQLITE3")
    option(BUILD_SQLITE3_ON "Build SQLITE3" OFF)
else ()
    message("-- Find SQLITE3_DIR success:${SQLITE3_DIR}")
    set(SQLITE3_LIBS sqlite3)
    option(BUILD_SQLITE3_ON "Build SQLITE3" ON)
    set(SQLITE3_INCLUDE_DIR "${SQLITE3_DIR}/include")
    set(SQLITE3_LIB_DIR "${SQLITE3_DIR}/${TARGET_ARCHITECTURE}/lib/")
    include_directories(${SQLITE3_INCLUDE_DIR})
    link_directories(${SQLITE3_LIB_DIR})
endif ()
