set(SQLITE3_DIR "" CACHE PATH "location of libraries")
if (NOT DEFINED SQLITE3_DIR OR SQLITE3_DIR STREQUAL "")
    message("-- Find SQLITE3_DIR failed,Please set SQLITE3_DIR with -D SQLITE3_DIR=/usr/local/SQLITE3")
    option(BUILD_SQLITE3_ON "Build SQLITE3" OFF)
else ()
    message("-- Find SQLITE3_DIR success:${SQLITE3_DIR}")
    option(BUILD_SQLITE3_ON "Build SQLITE3" ON)
    if (WIN32)
        if(CMAKE_BUILD_TYPE STREQUAL "Debug")
            set(SQLITE3_LIBS_SUFFIX "d")
            set(SQLITE3_LIB_DIR "${SQLITE3_DIR}/${TARGET_ARCHITECTURE}-windows/Debug/lib")
        else()
            set(SQLITE3_LIBS_SUFFIX "")
            set(SQLITE3_LIB_DIR "${SQLITE3_DIR}/${TARGET_ARCHITECTURE}-windows/lib")
        endif()
        set(SQLITE3_LIBS fmtd${SQLITE3_LIBS_SUFFIX} spdlogd${SQLITE3_LIBS_SUFFIX})
        set(SQLITE3_INCLUDE_DIR "${SQLITE3_DIR}/${TARGET_ARCHITECTURE}-windows/include")
    else ()
        set(SQLITE3_INCLUDE_DIR "${SQLITE3_DIR}/include")
        set(SQLITE3_LIB_DIR "${SQLITE3_DIR}/lib/")
    endif ()
    set(SQLITE3_LIBS sqlite3)
    include_directories(${SQLITE3_INCLUDE_DIR})
    link_directories(${SQLITE3_LIB_DIR})
endif ()
