set(HASP_ADAPTER_DIR "" CACHE PATH "location of libraries")
if (NOT DEFINED HASP_ADAPTER_DIR OR HASP_ADAPTER_DIR STREQUAL "")
    message("-- Find HASP_ADAPTER_DIR failed,Please set HASP_ADAPTER_DIR with -D HASP_ADAPTER_DIR=/usr/local/HASP_ADAPTER")
    option(BUILD_HASP_ADAPTER_ON "Build HASP_ADAPTER" OFF)
else ()
    message("-- Find HASP_ADAPTER_DIR success:${HASP_ADAPTER_DIR}")
    if (WIN32)
        if (TARGET_ARCHITECTURE STREQUAL "x86")
            set(HASP_ADAPTER_LIBS  libhasp_windows_34033)
        else ()
            set(HASP_ADAPTER_LIBS   libhasp_windows_x64_34033)
        endif ()
    else ()
        set(HASP_ADAPTER_LIBS  hasp_linux_x86_64_34033)
    endif ()
    option(BUILD_HASP_ADAPTER_ON "Build HASP_ADAPTER" ON)
    set(HASP_ADAPTER_INCLUDE_DIR "${HASP_ADAPTER_DIR}/include")
    set(HASP_ADAPTER_LIB_DIR "${HASP_ADAPTER_DIR}/lib/")
    include_directories(${HASP_ADAPTER_INCLUDE_DIR})
    link_directories(${HASP_ADAPTER_LIB_DIR})
endif ()
