SET(BREAKPAD_DIR "" CACHE PATH "Location of libraries")
if (NOT DEFINED BREAKPAD_DIR OR BREAKPAD_DIR STREQUAL "")
    message("-- Find BREAKPAD_DIR failed,Please set BREAKPAD_DIR with -D BREAKPAD_DIR=/usr/local/breakpad")
    option(BUILD_BREAKPAD_ON "Build BREAKPAD" OFF)
else ()
    message("-- Find BREAKPAD_DIR success:${BREAKPAD_DIR}")
    option(BUILD_BREAKPAD_ON "Build BREAKPAD" ON)
    if (WIN32)
        if(CMAKE_BUILD_TYPE STREQUAL "Debug")
            set(BREAKPAD_LIBS_SUFFIX "d")
            set(BREAKPAD_LIB_DIR "${BREAKPAD_DIR}/${TARGET_ARCHITECTURE}-windows/debug/lib/")
        else()
            set(BREAKPAD_LIBS_SUFFIX "")
            set(BREAKPAD_LIB_DIR "${BREAKPAD_DIR}/${TARGET_ARCHITECTURE}-windows/lib/")
        endif()
        set(BREAKPAD_INCLUDE_DIR "${BREAKPAD_DIR}/${TARGET_ARCHITECTURE}-windows/include/")
        set(BREAKPAD_LIBS libbreakpad_client${BREAKPAD_LIBS_SUFFIX} libdisasm${BREAKPAD_LIBS_SUFFIX})
    else ()
        set(BREAKPAD_INCLUDE_DIR "${BREAKPAD_DIR}/include/breakpad")
        set(BREAKPAD_LIB_DIR "${BREAKPAD_DIR}/lib")
        if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 7.0 AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 8.0)
            # GCC 7 特定的设置
            set(BREAKPAD_LIBS breakpad_client disasm pthread stdc++fs)
        else ()
            set(BREAKPAD_LIBS breakpad_client disasm pthread)
        endif()
    endif ()
    include_directories(${BREAKPAD_INCLUDE_DIR})
    link_directories(${BREAKPAD_LIB_DIR})
endif ()
