set(JADE_TOOLS_DIR "" CACHE PATH "location of libraries")
if (NOT DEFINED JADE_TOOLS_DIR OR JADE_TOOLS_DIR STREQUAL "")
    message("-- Find JADE_TOOLS_DIR failed,Please set JADE_TOOLS_DIR with -D JADE_TOOLS_DIR=/usr/local/JADE_TOOLS")
    option(BUILD_JADE_TOOLS_ON "Build JADE_TOOLS" OFF)
else ()
    message("-- Find JADE_TOOLS_DIR success:${JADE_TOOLS_DIR}")
    if (WIN32)
        set(JADE_TOOLS_INCLUDE_DIR "${JADE_TOOLS_DIR}/${TARGET_ARCHITECTURE}-windows/include/")
        if(CMAKE_BUILD_TYPE STREQUAL "Debug")
            set(JADE_TOOLS_LIBS_SUFFIX "d")
            set(JADE_TOOLS_LIB_DIR "${JADE_TOOLS_DIR}/${TARGET_ARCHITECTURE}-windows/debug/lib/")
        else()
            set(JADE_TOOLS_LIBS_SUFFIX "")
            set(JADE_TOOLS_LIB_DIR "${JADE_TOOLS_DIR}/${TARGET_ARCHITECTURE}-windows/lib/")
        endif()
        set(JADE_TOOLS_LIBS jade_tools${JADE_TOOLS_LIBS_SUFFIX} )
    else ()
        set(JADE_TOOLS_INCLUDE_DIR "${JADE_TOOLS_DIR}/include")
        set(JADE_TOOLS_LIB_DIR "${JADE_TOOLS_DIR}/lib/")
    endif ()
    include_directories(${JADE_TOOLS_INCLUDE_DIR})
    link_directories(${JADE_TOOLS_LIB_DIR})
endif ()
