set(SPDLOG_DIR "" CACHE PATH "location of libraries")
if (NOT DEFINED SPDLOG_DIR OR SPDLOG_DIR STREQUAL "")
    message("-- Find SPDLOG_DIR failed,Please set SPDLOG_DIR with -D SPDLOG_DIR=/usr/local/spdlog")
    option(BUILD_SPDLOG_ON "Build spdlog" OFF)
else ()
    option(BUILD_SPDLOG_ON "Build spdlog" ON)
    message("-- Find SPDLOG_DIR success:${SPDLOG_DIR}")
    if (WIN32)
        if(CMAKE_BUILD_TYPE STREQUAL "Debug")
            set(SPDLOG_LIBS_SUFFIX "d")
            set(SPDLOG_LIB_DIR "${SPDLOG_DIR}/${TARGET_ARCHITECTURE}-windows/Debug/lib")
        else()
            set(SPDLOG_LIBS_SUFFIX "")
            set(SPDLOG_LIB_DIR "${SPDLOG_DIR}/${TARGET_ARCHITECTURE}-windows/lib")
        endif()
        set(SPDLOG_LIBS fmt${SPDLOG_LIBS_SUFFIX} spdlog${SPDLOG_LIBS_SUFFIX})
        set(SPDLOG_INCLUDE_DIR "${SPDLOG_DIR}/${TARGET_ARCHITECTURE}-windows/include")
    else ()
        set(SPDLOG_INCLUDE_DIR "${SPDLOG_DIR}/include")
        set(SPDLOG_LIBS fmt)
    endif ()
    include_directories(${SPDLOG_INCLUDE_DIR})
    link_directories(${SPDLOG_LIB_DIR})
endif ()
