SET(CUDA_DIR "" CACHE PATH "Location of libraries")
if (NOT DEFINED CUDA_DIR OR CUDA_DIR STREQUAL "")
    message("-- Find CUDA_DIR failed,Please set CUDA_DIR with -D CUDA_DIR=/usr/local/cuda")
    option(BUILD_CUDA_ON "Build cuda" OFF)
else ()
    message("-- Find CUDA_DIR success:${CUDA_DIR}")
    option(BUILD_CUDA_ON "Build cuda" OFF)
    set(CUDA_LIBS nvml)
endif ()
set(CUDA_INCLUDE_DIR "${CUDA_DIR}/include")
if (NOT WIN32)
    set(CUDA_LIB_DIR "${CUDA_DIR}/lib64")
else ()
    set(CUDA_LIB_DIR "${CUDA_DIR}/lib/x64")
endif ()