name: Prepare Release

on: workflow_call

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          repository: jadehh/release
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          repository: jadehh/jade_tools
          ref: main
          path: code
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup branch and files
        run: |
          git config --global user.email "jadehh@live.com"
          git config --global user.name "jade"
          
          check_name=$(git rev-list --max-parents=0 HEAD)
          # branch_name=$(cd code/ && git rev-parse --abbrev-ref HEAD) # 是release分支的名称，如果当前分支是main，则固定分支的名称
          branch_name=jade_tools
          tag=$(cd code/ && git describe --abbrev=0 --tags)
          
          echo "Base commit: $check_name"
          echo "Branch name: $branch_name"
          echo "Tag: $tag"
          git checkout $check_name -b $branch_name  ##分支不存在用这个
          ## git checkout $branch_name  ## 分支已存在用这个
          cd code/ && cmake -P .cmake/extractChangelog.cmake && cd ../
          cp -r code/RELEASE_NOTES.md README.md
          cp -r code/workflows/.github ./ && ls -la
          git add .github/workflows/release.yml
          git add .github/workflows/packing.yml
          git add README.md
          commit_msg="* 更新线阵相机管理服务${tag}"
          git commit -a -m "$commit_msg"
          git tag -fa ${branch_name}-${tag} -m "${commit_msg}"

      - name: Upload to target repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          repository: jadehh/release
          directory: .
          branch: jade_tools
          force: true
          tags: true
        env:
          GITHUB_ACTOR: jadehh